### ISSUE TITLE
关于训练时长的问题

### ISSUE THREAD

**Issue by qqlong4580** [bubbliiiing/srgan-pytorch#3]
从B站关注博主很久了，以前的tensorflow版本也用过，用了新的重制版试了一下感觉比之前的效果要好很多，在CSDN博客上看到博主说用1660ti训练了两天左右，但是我自己用了Kaggle上的GPU训练用的batch_size=16但是12个小时左右才15个epoch，是不是还要设置某些东西呢，训练集使用的Yahoo MirFlickr25k数据集
![屏幕截图 2022-07-13 135331](https://user-images.githubusercontent.com/109200183/178661684-9821a4ed-16d7-4def-9865-995d4311a2d5.png)

**Comment by bubbliiiing** [comment]
Kaggle？K80不快的呢，两天左右应该不是MirFlickr25k，是另一个数据集
